<a href="https://colab.research.google.com/github/gantapriyanka1325/DeepLearningLab/blob/main/program1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [4]:
#1.Create Tensors and perform basic operations with tensors

import numpy as np

# Create tensors (2D arrays)
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])

print("Tensor A:\n", A)
print("Tensor B:\n", B)



Tensor A:
 [[1 2]
 [3 4]]
Tensor B:
 [[5 6]
 [7 8]]


In [5]:
#Basic operations
add_result = A + B
sub_result = A - B
mul_result = A * B          # Element-wise multiplication
div_result = A / B          # Element-wise division
matmul_result = A @ B       # Matrix multiplication
print("\nAddition:\n", add_result)
print("\nSubtraction:\n", sub_result)
print("\nElement-wise Multiplication:\n", mul_result)
print("\nElement-wise Division:\n", div_result)
print("\nMatrix Multiplication:\n", matmul_result)



Addition:
 [[ 6  8]
 [10 12]]

Subtraction:
 [[-4 -4]
 [-4 -4]]

Element-wise Multiplication:
 [[ 5 12]
 [21 32]]

Element-wise Division:
 [[0.2        0.33333333]
 [0.42857143 0.5       ]]

Matrix Multiplication:
 [[19 22]
 [43 50]]


In [6]:
#using tensor flow
import tensorflow as tf

# Create constant tensors
A = tf.constant([[1, 2], [3, 4]], dtype=tf.float32)
B = tf.constant([[5, 6], [7, 8]], dtype=tf.float32)

# Basic operations
add_result = tf.add(A, B)          # Addition
sub_result = tf.subtract(A, B)     # Subtraction
mul_result = tf.multiply(A, B)     # Element-wise multiplication
div_result = tf.divide(A, B)       # Element-wise division
matmul_result = tf.matmul(A, B)    # Matrix multiplication

print("Addition:\n", add_result.numpy())
print("Subtraction:\n", sub_result.numpy())
print("Multiplication:\n", mul_result.numpy())
print("Division:\n", div_result.numpy())
print("Matrix Multiplication:\n", matmul_result.numpy())

Addition:
 [[ 6.  8.]
 [10. 12.]]
Subtraction:
 [[-4. -4.]
 [-4. -4.]]
Multiplication:
 [[ 5. 12.]
 [21. 32.]]
Division:
 [[0.2        0.33333334]
 [0.42857143 0.5       ]]
Matrix Multiplication:
 [[19. 22.]
 [43. 50.]]
