<a href="https://colab.research.google.com/github/gantapriyanka1325/DeepLearningLab/blob/main/program2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
#2: Create Tensors and Apply Split & Merge Operations + Statistics Operations

import numpy as np
# Create a 3x4 tensor
data = np.arange(1, 13).reshape(3, 4)
print("Original Tensor:\n", data)



Original Tensor:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [3]:
# Split into 2 parts along columns (axis=1)
splits = np.split(data, 2, axis=1)
print("\nSplit Parts:")
for part in splits:
    print(part)



Split Parts:
[[ 1  2]
 [ 5  6]
 [ 9 10]]
[[ 3  4]
 [ 7  8]
 [11 12]]


In [4]:
# Merge back into original tensor
merged = np.concatenate(splits, axis=1)
print("\nMerged Tensor:\n", merged)




Merged Tensor:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [5]:
# Statistics
mean_val = np.mean(data)
max_val = np.max(data)
min_val = np.min(data)
sum_val = np.sum(data)
std_val = np.std(data)

print("\nStatistics:")
print(f"Mean: {mean_val}")
print(f"Max: {max_val}")
print(f"Min: {min_val}")
print(f"Sum: {sum_val}")
print(f"Standard Deviation: {std_val}")



Statistics:
Mean: 6.5
Max: 12
Min: 1
Sum: 78
Standard Deviation: 3.452052529534663


In [6]:
#using tensor flow
import tensorflow as tf

# Create a tensor
data = tf.constant([[1, 2, 3, 4],
                    [5, 6, 7, 8],
                    [9, 10, 11, 12]], dtype=tf.float32)

print("Original Tensor:\n", data.numpy())



Original Tensor:
 [[ 1.  2.  3.  4.]
 [ 5.  6.  7.  8.]
 [ 9. 10. 11. 12.]]


In [8]:
# Split into 2 parts along columns (axis=1)
splits = tf.split(data, num_or_size_splits=2, axis=1)

print("\nSplit Parts:")
for part in splits:
    print(part.numpy())


Split Parts:
[[ 1.  2.]
 [ 5.  6.]
 [ 9. 10.]]
[[ 3.  4.]
 [ 7.  8.]
 [11. 12.]]


In [9]:
# Merge back (concatenate along columns)
merged = tf.concat(splits, axis=1)
print("\nMerged Tensor:\n", merged.numpy())


Merged Tensor:
 [[ 1.  2.  3.  4.]
 [ 5.  6.  7.  8.]
 [ 9. 10. 11. 12.]]


In [10]:
# Statistics
mean_val = tf.reduce_mean(data)
max_val = tf.reduce_max(data)
min_val = tf.reduce_min(data)
sum_val = tf.reduce_sum(data)
std_val = tf.math.reduce_std(data)

print("\nStatistics:")
print(f"Mean: {mean_val.numpy()}")
print(f"Max: {max_val.numpy()}")
print(f"Min: {min_val.numpy()}")
print(f"Sum: {sum_val.numpy()}")
print(f"Standard Deviation: {std_val.numpy()}")


Statistics:
Mean: 6.5
Max: 12.0
Min: 1.0
Sum: 78.0
Standard Deviation: 3.452052593231201
