<a href="https://colab.research.google.com/github/gantapriyanka1325/DeepLearningLab/blob/main/program3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

3 Design single unit perception for classification of iris dataset without using predefined models

In [1]:
#Implementation of AND Gate
import numpy as np
import tensorflow as tf

# Example input data (4 samples, 2 features each)
X = tf.constant([[0.0, 0.0],
                 [0.0, 1.0],
                 [1.0, 0.0],
                 [1.0, 1.0]], dtype=tf.float32)

# Manually define weights and bias
W = tf.constant([[2.0],   # weight for feature 1
                 [2.0]],  # weight for feature 2
                dtype=tf.float32)
b = tf.constant([-3.0], dtype=tf.float32)  # bias



In [2]:
# Forward pass: z = XW + b
z = tf.matmul(X, W) + b

# Activation (step function or sigmoid)
y_step = tf.cast(z >= 0, tf.int32)# hard threshold (binary output)
y_sigmoid = tf.math.sigmoid(z) # soft probability

print("Inputs:\n", X.numpy())
print("Linear combination (z):\n", z.numpy())
print("Step output (Perceptron):\n", y_step.numpy())
print("Sigmoid output (probability):\n", y_sigmoid.numpy())



Inputs:
 [[0. 0.]
 [0. 1.]
 [1. 0.]
 [1. 1.]]
Linear combination (z):
 [[-3.]
 [-1.]
 [-1.]
 [ 1.]]
Step output (Perceptron):
 [[0]
 [0]
 [0]
 [1]]
Sigmoid output (probability):
 [[0.04742587]
 [0.26894143]
 [0.26894143]
 [0.7310586 ]]


IRIS DataSet

In [6]:
#1. Import Libraries
import tensorflow as tf
import pandas as pd
import numpy as np

In [7]:
#2. Load Dataset
df = pd.read_csv("/content/Iris.csv")

In [8]:
#3. Select Features
X = df.iloc[:, 0:2].values   # First 2 features (sepal length, sepal width)
y = df.iloc[:, -1].values    # Last column → species


In [9]:
#4. Convert to Binary Classification
y_binary = np.where(y == "Iris-setosa", 1.0, 0.0).astype(np.float32)


In [11]:
#5. Normalize Features
X = (X - X.mean(axis=0)) / X.std(axis=0)

In [12]:
#6. Convert Data to TensorFlow Tensor
X_tf = tf.constant(X, dtype=tf.float32)


In [13]:
#7. Define Weights and Bias
W = tf.constant([[1.0],
                 [-1.0]], dtype=tf.float32)
b = tf.constant([0.2], dtype=tf.float32)

In [14]:
#8. Forward Pass (Linear Combination)
z = tf.matmul(X_tf, W) + b

In [15]:
#9. Step Activation (Hard Perceptron)
y_pred_step = tf.cast(z >= 0, tf.int32)

In [16]:
#10. Sigmoid Activation (Soft Output)
y_pred_sigmoid = tf.math.sigmoid(z)

In [17]:
#11. Print Results
print("First 10 True labels (Setosa=1, Others=0):", y_binary[:10])
print("First 10 Step outputs:", y_pred_step.numpy().flatten()[:10])
print("First 10 Sigmoid probabilities:", y_pred_sigmoid.numpy().flatten()[:10])


First 10 True labels (Setosa=1, Others=0): [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
First 10 Step outputs: [0 0 0 1 0 0 1 0 1 0]
First 10 Sigmoid probabilities: [0.3498131  0.41230834 0.4777646  0.513812   0.39979607 0.29569322
 0.5310962  0.4165307  0.60182387 0.45768285]
